title: "Diptesh's Blog"
email: dipteshhh@gmail.com
description: >-
  Investigative journalism, tech and policy analysis by Diptesh Shahi Thakuri.
baseurl: "" 
url: "https://dipteshhh.github.io"
twitter_username: dipteshhh
github_username: dipteshhh

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
