title: "Diptesh Shahi Thakuri"
description: >-
  Independent blog by Diptesh Shahi Thakuri — exploring Nepal’s current affairs,
  transport reform, and global issues through the lens of investigative journalism
  and technology.

url: "https://dipteshhh.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Optional but helpful
markdown: kramdown
highlighter: rouge
