title: "Diptesh Shahi Thakuri"
email: diptesh@example.com
description: >-
  Investigative journalism meets global affairs & digital reform.
baseurl: "" # this is CRITICAL for user pages
url: "https://dipteshhh.github.io"

github_username: dipteshhh
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
